name: Credential 🔑
description: Social media or platform profile connected to an external organization or person
title: '|'
type: 'Credential 🔑'
projects: ["StaytunedLLP/17"]

body:
  - type: markdown
    attributes:
      value: |
        🚀 Speed Leads, Ship Every Day.

  - type: textarea
    attributes:
      label: Description
      value: |
        **Credential Name:**  
        **Type (e.g., API Key, OAuth Token, Password, Certificate):**  
        **Platform/Service (e.g., AWS, GitHub, Slack):**  
        **Associated Organization/Person:**  
        **Credential Owner (Internal Contact):**  
        **Credential Link/Location:**  
        **Access Level:** (e.g., Read, Write, Admin)  
        **Expiry/Rotation Date:**  

        ### Purpose of Credential
        Briefly describe why this credential exists and its intended use for StaytunedLLP or its projects.  
        - 

        ### Usage & Access
        List main systems, projects, or processes where this credential is used.  
        - 

        ### Security & Management
        Outline security controls, rotation policies, and storage details for this credential.  
        - 

        ### Success Metrics
        How will we measure the effectiveness and security of this credential?  
        - [Metric Name](Link) – Brief description

        ### Key Participants & Roles
        List the main participants (internal and external) and their responsibilities regarding this credential.  
        - 

        ### Recent Changes or Updates
        Outline recent rotations, access changes, or incidents relevant to this credential.  
        - 

        ### Additional Context
        Add any relevant background, links, or supporting information.
