name: Story 🌟
description: User-focused narrative or journey
title: '|'
type: 'Story 🌟'
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: |
        🚀 Speed Leads, Ship Every Day.

  - type: textarea
    attributes:
      label: Description
      value: |
        As a
        I want to
        so that

        ### Why this is important

        1. 

        ### Details

        1. [File Name](Link) - Brief description of the file

        ### Diagrams

        1. [Diagram Name](Link) - Brief description of the diagram

        ### Designs

        1. [Design Name](Link) - Brief description of the design

        ### Feature Association

        #00 

        ### Acceptance Criteria

        - [ ] 

        ### Additional Context
